DELIMITER $$

DROP PROCEDURE IF EXISTS `DELETE_ARTICLE`$$

CREATE PROCEDURE `DELETE_ARTICLE`(IN lid INT,OUT result INT)
BEGIN
	DELETE FROM CATEGORY_DETAILS WHERE ARTICLE_ID=lid;
	IF (EXISTS (SELECT 1 FROM COMMENTS_DETAILS WHERE ARTICLE_ID=lid))THEN
	DELETE FROM COMMENTS_DETAILS WHERE ARTICLE_ID=lid;
	END IF;
	DELETE FROM ARTICLES WHERE ID=lid;
	SET result=1;
    END$$

DELIMITER ;