DELIMITER $$


DROP PROCEDURE IF EXISTS `REGISTER`$$

CREATE PROCEDURE `REGISTER`(IN LNAME VARCHAR(30),IN LUSER_NAME VARCHAR(30),IN LPASSWORD VARCHAR(30),IN LEMAIL_ID VARCHAR(30),LPHONE_NO VARCHAR(10),OUT RESULT VARCHAR(100))
BEGIN
	IF (ISVALID(LUSER_NAME))THEN
	INSERT INTO USERS (NAME,USER_NAME,PASSWORD,EMAIL_ID,PHONE_NUMBER) VALUES(LNAME,LUSER_NAME,LPASSWORD,LEMAIL_ID,LPHONE_NO);
	SET RESULT="Registered successfully";
	ELSE
	SET RESULT="user name already exists";
	END IF;
    END$$

DELIMITER ;