DELIMITER $$

DROP FUNCTION IF EXISTS `ISVALID_USER_NAME`$$

CREATE FUNCTION `ISVALID_USER_NAME`(LUSER_NAME VARCHAR(30)) RETURNS TINYINT(1)
BEGIN
	DECLARE RESULT BOOLEAN DEFAULT FALSE;
	IF (NOT EXISTS(SELECT 1 FROM USERS WHERE USER_NAME=LUSER_NAME))THEN
	SET RESULT=TRUE;
	END IF;
	RETURN RESULT;
    END$$

DELIMITER ;