DELIMITER $$

DROP FUNCTION IF EXISTS `ISVALID_PASSWORD`$$

CREATE FUNCTION `ISVALID_PASSWORD`(LUSER_NAME VARCHAR(30),LPASSWORD VARCHAR(30)) RETURNS TINYINT(1)
BEGIN
	DECLARE RESULT BOOLEAN DEFAULT FALSE;
	IF (EXISTS(SELECT 1 FROM USERS WHERE USER_NAME=LUSER_NAME AND PASSWORD=LPASSWORD))THEN
	SET RESULT=TRUE;
	END IF;
	RETURN RESULT;
    END$$

DELIMITER ;